### ISSUE TITLE
Can you make a version that doesn't delete any files and is just annoying?

### ISSUE THREAD

**Issue by AstroOrbis** [FlyTechVideos/000.exe#1]
Like a prank version, one that just makes tons of files to remove and doesn't supress any keystrokes or delete reg files

**Comment by MichaelEpicA** [comment]
ok

**Comment by ghost** [comment]
fancy seeing you here.  
not sure if this is possible, because there are many other files automatically being written from the resources. you can try decompiling each file and converting them into c# code instead.

**Comment by AstroOrbis** [comment]
I forgot about this issue kekw
Now that I have minor C# experience, I’ll try!

**Comment by SmilerRyan** [comment]
> I forgot about this issue kekw
> Now that I have minor C# experience, I’ll try!

Not sure if you're still interested, I've made a "safe" version that:

- Plays the street animation
- Sets the User's desktop files to "hidden"
- Creates new files (1x rtf, 400x png)

Here's a [source/binary](https://github.com/FlyTechVideos/000exe/files/7229771/OOO2.zip) download.

**Comment by AstroOrbis** [comment]
Allright, thanks!

**Comment by ghost** [comment]
you can download it make your own repository and put 000 in it and try to find and delete the code that does that.
